from Items import Skull_basher, Desolator, Butterfly
a = Butterfly()
b = Desolator()
c = Skull_basher()
a.buy('Eaglesong', 1)
a.buy('Claymore', 1)
a.buy('Talisman of evasion', 1)
a.craft()
a.info()
b.buy('Mithril hammer', 2)
b.buy('Bright stone', 1)
b.craft()
b.info()
c.buy('Mithril hammer', 1)
c.buy('Belt of strength', 1)
c.buy('Recept', 1)
c.craft()
c.info()
